<?php defined('SYSPATH') OR die('No direct script access.');
class Admin_Ajax_MediaControl extends Admin_Ajax {
    
    const ERROR_CODE_MEDIACONTROL_PATH_EMPTY = 'MEDIACONTROL_PATH_EMPTY';
    const ERROR_CODE_MEDIACONTROL_UNKNOWN_ACTION = 'MEDIACONTROL_UNKNOWN_ACTION';
    const ERROR_CODE_MEDIACONTROL_UNKNOWN_ERROR = 'MEDIACONTROL_UNKNOWN_ERROR';
    const ERROR_CODE_MEDIACONTROL_CATEGORY_NOT_FOUND = 'MEDIACONTROL_CATEGORY_NOT_FOUND';
    const ERROR_CODE_MEDIACONTROL_CATEGORY_FOLDER_NOT_FOUND = 'MEDIACONTROL_CATEGORY_FOLDER_NOT_FOUND';
    const ERROR_CODE_MEDIACONTROL_CATEGORY_FILE_NOT_FOUND = 'MEDIACONTROL_CATEGORY_FILE_NOT_FOUND';
    const ERROR_CODE_MEDIACONTROL_CATEGORY_FOLDER_EXISTS = 'MEDIACONTROL_CATEGORY_FOLDER_EXISTS';
    const ERROR_CODE_MEDIACONTROL_FOLDER_NAME_EMPTY = 'MEDIACONTROL_FOLDER_NAME_EMPTY';
    const ERROR_CODE_MEDIACONTROL_CATEGORY_FOLDER_NOT_EMPTY = 'MEDIACONTROL_CATEGORY_FOLDER_NOT_EMPTY';

    
    protected function _addErrorDescription(){
        $lst = array(
            self::ERROR_CODE_MEDIACONTROL_PATH_EMPTY => 'path is empty',
            self::ERROR_CODE_MEDIACONTROL_UNKNOWN_ACTION => 'unknown action',
            self::ERROR_CODE_MEDIACONTROL_UNKNOWN_ERROR => 'unknown error',
            self::ERROR_CODE_MEDIACONTROL_CATEGORY_NOT_FOUND => 'system error',
        	self::ERROR_CODE_MEDIACONTROL_CATEGORY_FOLDER_NOT_FOUND => 'folder not found',
        	self::ERROR_CODE_MEDIACONTROL_CATEGORY_FOLDER_EXISTS => 'folder exists',	
        	self::ERROR_CODE_MEDIACONTROL_FOLDER_NAME_EMPTY => 'folder name is empty',		
			self::ERROR_CODE_MEDIACONTROL_CATEGORY_FILE_NOT_FOUND => 'file not found',
        	self::ERROR_CODE_MEDIACONTROL_CATEGORY_FOLDER_NOT_EMPTY => 'folder not empty'
        );
        
        $this->errorDescription = array_merge($this->errorDescription, $lst);
    }
}